/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SsoCallbackRouteImport } from './app/sso-callback'
import { Route as SigningOutRouteImport } from './app/signing-out'
import { Route as SigningInRouteImport } from './app/signing-in'
import { Route as GoodbyeRouteImport } from './app/goodbye'
import { Route as PolicyRouteImport } from './app/_policy'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as IndexRouteImport } from './app/index'
import { Route as ApiUploadthingRouteImport } from './app/api/uploadthing'
import { Route as PolicyTermsOfServiceRouteImport } from './app/_policy/terms-of-service'
import { Route as PolicyPrivacyPolicyRouteImport } from './app/_policy/privacy-policy'
import { Route as AuthenticatedSettingsRouteImport } from './app/_authenticated/settings'
import { Route as AuthenticatedPricingRouteImport } from './app/_authenticated/pricing'
import { Route as AuthenticatedNewRouteImport } from './app/_authenticated/new'
import { Route as AuthenticatedHomeRouteImport } from './app/_authenticated/home'
import { Route as AuthenticatedSettingsIndexRouteImport } from './app/_authenticated/settings/index'
import { Route as ApiFalProxyRouteImport } from './app/api/fal/proxy'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './app/_authenticated/settings/preferences'
import { Route as AuthenticatedSettingsContactRouteImport } from './app/_authenticated/settings/contact'
import { Route as AuthenticatedSettingsAccountRouteImport } from './app/_authenticated/settings/account'
import { Route as AuthenticatedChatIdRouteImport } from './app/_authenticated/chat.$id'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningOutRoute = SigningOutRouteImport.update({
  id: '/signing-out',
  path: '/signing-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningInRoute = SigningInRouteImport.update({
  id: '/signing-in',
  path: '/signing-in',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyTermsOfServiceRoute = PolicyTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => PolicyRoute,
} as any)
const PolicyPrivacyPolicyRoute = PolicyPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PolicyRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiFalProxyRoute = ApiFalProxyRouteImport.update({
  id: '/api/fal/proxy',
  path: '/api/fal/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsContactRoute =
  AuthenticatedSettingsContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/signing-in': typeof SigningInRoute
  '/signing-out': typeof SigningOutRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new': typeof AuthenticatedNewRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/privacy-policy': typeof PolicyPrivacyPolicyRoute
  '/terms-of-service': typeof PolicyTermsOfServiceRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/api/fal/proxy': typeof ApiFalProxyRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/signing-in': typeof SigningInRoute
  '/signing-out': typeof SigningOutRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new': typeof AuthenticatedNewRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/privacy-policy': typeof PolicyPrivacyPolicyRoute
  '/terms-of-service': typeof PolicyTermsOfServiceRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/api/fal/proxy': typeof ApiFalProxyRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_policy': typeof PolicyRouteWithChildren
  '/goodbye': typeof GoodbyeRoute
  '/signing-in': typeof SigningInRoute
  '/signing-out': typeof SigningOutRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_policy/privacy-policy': typeof PolicyPrivacyPolicyRoute
  '/_policy/terms-of-service': typeof PolicyTermsOfServiceRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/contact': typeof AuthenticatedSettingsContactRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/api/fal/proxy': typeof ApiFalProxyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goodbye'
    | '/signing-in'
    | '/signing-out'
    | '/sso-callback'
    | '/home'
    | '/new'
    | '/pricing'
    | '/settings'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/uploadthing'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/api/fal/proxy'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goodbye'
    | '/signing-in'
    | '/signing-out'
    | '/sso-callback'
    | '/home'
    | '/new'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/uploadthing'
    | '/chat/$id'
    | '/settings/account'
    | '/settings/contact'
    | '/settings/preferences'
    | '/api/fal/proxy'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_policy'
    | '/goodbye'
    | '/signing-in'
    | '/signing-out'
    | '/sso-callback'
    | '/_authenticated/home'
    | '/_authenticated/new'
    | '/_authenticated/pricing'
    | '/_authenticated/settings'
    | '/_policy/privacy-policy'
    | '/_policy/terms-of-service'
    | '/api/uploadthing'
    | '/_authenticated/chat/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/contact'
    | '/_authenticated/settings/preferences'
    | '/api/fal/proxy'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PolicyRoute: typeof PolicyRouteWithChildren
  GoodbyeRoute: typeof GoodbyeRoute
  SigningInRoute: typeof SigningInRoute
  SigningOutRoute: typeof SigningOutRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiFalProxyRoute: typeof ApiFalProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing-out': {
      id: '/signing-out'
      path: '/signing-out'
      fullPath: '/signing-out'
      preLoaderRoute: typeof SigningOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing-in': {
      id: '/signing-in'
      path: '/signing-in'
      fullPath: '/signing-in'
      preLoaderRoute: typeof SigningInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_policy': {
      id: '/_policy'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_policy/terms-of-service': {
      id: '/_policy/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PolicyTermsOfServiceRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/_policy/privacy-policy': {
      id: '/_policy/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PolicyPrivacyPolicyRouteImport
      parentRoute: typeof PolicyRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/fal/proxy': {
      id: '/api/fal/proxy'
      path: '/api/fal/proxy'
      fullPath: '/api/fal/proxy'
      preLoaderRoute: typeof ApiFalProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/contact': {
      id: '/_authenticated/settings/contact'
      path: '/contact'
      fullPath: '/settings/contact'
      preLoaderRoute: typeof AuthenticatedSettingsContactRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsContactRoute: typeof AuthenticatedSettingsContactRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsContactRoute: AuthenticatedSettingsContactRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PolicyRouteChildren {
  PolicyPrivacyPolicyRoute: typeof PolicyPrivacyPolicyRoute
  PolicyTermsOfServiceRoute: typeof PolicyTermsOfServiceRoute
}

const PolicyRouteChildren: PolicyRouteChildren = {
  PolicyPrivacyPolicyRoute: PolicyPrivacyPolicyRoute,
  PolicyTermsOfServiceRoute: PolicyTermsOfServiceRoute,
}

const PolicyRouteWithChildren =
  PolicyRoute._addFileChildren(PolicyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PolicyRoute: PolicyRouteWithChildren,
  GoodbyeRoute: GoodbyeRoute,
  SigningInRoute: SigningInRoute,
  SigningOutRoute: SigningOutRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiFalProxyRoute: ApiFalProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
