/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PdsSsrValidationRouteImport } from "./routes/pds-ssr-validation";

const PdsSsrValidationRoute = PdsSsrValidationRouteImport.update({
  id: "/pds-ssr-validation",
  path: "/pds-ssr-validation",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/pds-ssr-validation": typeof PdsSsrValidationRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/pds-ssr-validation": typeof PdsSsrValidationRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/pds-ssr-validation": typeof PdsSsrValidationRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/pds-ssr-validation";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/pds-ssr-validation";
  id: "__root__" | "/" | "/pds-ssr-validation";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PdsSsrValidationRoute: typeof PdsSsrValidationRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/pds-ssr-validation": {
      id: "/pds-ssr-validation";
      path: "/pds-ssr-validation";
      fullPath: "/pds-ssr-validation";
      preLoaderRoute: typeof PdsSsrValidationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PdsSsrValidationRoute: PdsSsrValidationRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
