import { gateway } from "@ai-sdk/gateway";
import { openrouter } from "@openrouter/ai-sdk-provider";

import type { LanguageModel } from "./types";

export const languageModels = {
  "gemini-2.0-flash": {
    provider: "Google",
    name: "Gemini 2.0 Flash",
    model: openrouter("google/gemini-2.0-flash-001"),
    cost: { in: 0.1, out: 0.4, other: 0 },
    available: false,
  },
  "gemini-2.5-flash-lite": {
    provider: "Google",
    name: "Gemini 2.5 Flash Lite",
    model: openrouter("google/gemini-2.5-flash-lite-preview-09-2025"),
    cost: { in: 0.1, out: 0.4, other: 0 },
    available: false,
  },
  "gemini-2.5-flash": {
    provider: "Google",
    name: "Gemini 2.5 Flash",
    model: openrouter("google/gemini-2.5-flash"),
    cost: { in: 0.3, out: 2.5, other: 0 },
    available: false,
  },
  "gemini-2.5-pro": {
    provider: "Google",
    name: "Gemini 2.5 Pro",
    model: openrouter("google/gemini-2.5-pro"),
    cost: { in: 2.5, out: 15, other: 0 },
    available: false,
  },
  "gemini-3-flash": {
    provider: "Google",
    name: "Gemini 3 Flash",
    model: openrouter("google/gemini-3-flash-preview"),
    cost: { in: 0.5, out: 3, other: 0 },
    available: true,
  },
  "gemini-3-pro": {
    provider: "Google",
    name: "Gemini 3 Pro",
    model: openrouter("google/gemini-3-pro"),
    cost: { in: 2, out: 15, other: 0 },
    available: false,
  },
  "o4-mini": {
    provider: "OpenAI",
    name: "o4 mini",
    model: openrouter("openai/o4-mini"),
    cost: { in: 1.1, out: 4.4, other: 0 },
    available: false,
  },
  o3: {
    provider: "OpenAI",
    name: "o3",
    model: openrouter("openai/o3-2025-04-16"),
    cost: { in: 2, out: 8, other: 0 },
    available: false,
  },
  "oss-120b": {
    provider: "OpenAI",
    name: "GPT-OSS 120b",
    model: openrouter("openai/gpt-oss-120b"),
    cost: { in: 0.15, out: 0.6, other: 0 },
    available: false,
  },
  "oss-20b": {
    provider: "OpenAI",
    name: "GPT-OSS 20b",
    model: openrouter("openai/gpt-oss-20b"),
    cost: { in: 0.05, out: 0.2, other: 0 },
    available: false,
  },
  "gpt-5.2": {
    provider: "OpenAI",
    name: "GPT-5.2",
    model: openrouter("openai/gpt-5.2"),
    cost: { in: 1.75, out: 14, other: 0 },
    available: false,
  },
  "gpt-5.2-chat": {
    provider: "OpenAI",
    name: "GPT-5.2 Chat",
    model: openrouter("openai/gpt-5.2-chat"),
    cost: { in: 1.75, out: 14, other: 0 },
    available: false,
  },
  "gpt-5-mini": {
    provider: "OpenAI",
    name: "GPT-5 Mini",
    model: openrouter("openai/gpt-5-mini"),
    cost: { in: 0.25, out: 2, other: 0 },
    available: false,
  },
  "gpt-5-nano": {
    provider: "OpenAI",
    name: "GPT-5 Nano",
    model: openrouter("openai/gpt-5-nano"),
    cost: { in: 0.05, out: 0.4, other: 0 },
    available: false,
  },
  "gpt-5.3-chat": {
    provider: "OpenAI",
    name: "GPT 5.3",
    model: openrouter("openai/gpt-5.3-chat"),
    cost: { in: 1.75, out: 14, other: 0 },
    available: true,
  },
  "claude-4.5-haiku": {
    provider: "Anthropic",
    name: "Claude 4.5 Haiku",
    model: openrouter("anthropic/claude-haiku-4.5"),
    cost: { in: 1, out: 5, other: 0 },
    available: false,
  },
  "claude-4.5-sonnet": {
    provider: "Anthropic",
    name: "Claude 4.5 Sonnet",
    model: openrouter("anthropic/claude-sonnet-4.5"),
    cost: { in: 3, out: 15, other: 0 },
    available: false,
  },
  "claude-4.6-sonnet": {
    provider: "Anthropic",
    name: "Claude Sonnet 4.6",
    model: openrouter("anthropic/claude-sonnet-4.6"),
    cost: { in: 3, out: 15, other: 0 },
    available: true,
  },
  "claude-opus-4.5": {
    provider: "Anthropic",
    name: "Claude Opus 4.5",
    model: openrouter("anthropic/claude-opus-4.5"),
    cost: { in: 5, out: 25, other: 0 },
    available: false,
  },
  "claude-opus-4.6": {
    provider: "Anthropic",
    name: "Claude Opus 4.6",
    model: openrouter("anthropic/claude-opus-4.6"),
    cost: { in: 5, out: 25, other: 0 },
    available: true,
  },
  "grok-3-mini": {
    provider: "xAI",
    name: "Grok 3 Mini",
    model: openrouter("x-ai/grok-3-mini"),
    cost: { in: 0.3, out: 0.5, other: 0 },
    available: false,
  },
  "grok-4": {
    provider: "xAI",
    name: "Grok 4",
    model: openrouter("x-ai/grok-4"),
    cost: { in: 3, out: 15, other: 0 },
    available: false,
  },
  "grok-4-fast": {
    provider: "xAI",
    name: "Grok 4 Fast",
    model: openrouter("x-ai/grok-4-fast"),
    cost: { in: 0.2, out: 0.5, other: 0 },
    available: false,
  },
  "grok-4.1-fast": {
    provider: "xAI",
    name: "Grok 4.1 Fast",
    model: openrouter("x-ai/grok-4.1-fast"),
    cost: { in: 0.2, out: 0.5, other: 0 },
    available: false,
  },
  "grok-4.20": {
    provider: "xAI",
    name: "Grok 4.20",
    model: gateway("xai/grok-4.20-reasoning-beta"),
    cost: { in: 2, out: 6, other: 0 },
    available: false,
  },
  "grok-4.3": {
    provider: "xAI",
    name: "Grok 4.3",
    model: gateway("xai/grok-4.3"),
    cost: { in: 1.25, out: 2.5, other: 0 },
    available: true,
  },
  sonar: {
    provider: "Perplexity",
    name: "Sonar",
    model: openrouter("perplexity/sonar"),
    cost: { in: 1, out: 1, other: 0.005 },
    available: false,
  },
  "sonar-reasoning-pro": {
    provider: "Perplexity",
    name: "Sonar Reasoning Pro",
    model: openrouter("perplexity/sonar-reasoning-pro"),
    cost: { in: 2, out: 8, other: 0.005 },
    available: false,
  },
  "switchpoint-router": {
    provider: "Switchpoint",
    name: "Switchpoint Router",
    model: openrouter("switchpoint/router"),
    cost: { in: 0.85, out: 3.4, other: 0 },
    available: false,
  },
  "kimi-k2": {
    provider: "Moonshot",
    name: "Kimi K2",
    model: openrouter("moonshotai/kimi-k2-0905"),
    cost: { in: 0.3, out: 1.2, other: 0 },
    available: false,
  },
  "mercury-coder": {
    provider: "Inception",
    name: "Mercury Coder",
    model: openrouter("inception/mercury-coder"),
    cost: { in: 0.25, out: 1, other: 0 },
    available: false,
  },
  "qwen-3-235b": {
    provider: "Alibaba",
    name: "Qwen 3 235B",
    model: openrouter("@preset/qwen-cerebras"),
    cost: { in: 0.6, out: 1.2, other: 0 },
    available: false,
  },
  "glm-4.5": {
    provider: "z-ai",
    name: "GLM 4.5",
    model: openrouter("z-ai/glm-4.5"),
    cost: { in: 0.6, out: 2.2, other: 0 },
    available: false,
  },
} as const satisfies Record<string, LanguageModel>;
